version: '3.3'

services:
  mysql: 
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    env_file: ./env/mysql.env
    ports:
      - "3366:3306"

  mysqld-exporter:
    container_name: mysqld-exporter
    image: prom/mysqld-exporter
    ports:
      - "9104:9104"
    environment:
      - DATA_SOURCE_NAME="exporter:123456@(mysql:3306)/"

  rabbitmq:
    build:
      context: .
      dockerfile: Dockerfile-rabbitmq
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - "15692:15692"

  app-python:
    build:
      context: .
      dockerfile: Dockerfile-python
    image: app-python
    container_name: app-python
    depends_on:
      - rabbitmq
    ports:
      - "8000:8000"
    env_file: ./env/python.env

  app-node:
    build:
      context: .
      dockerfile: Dockerfile-node
    image: app-node
    container_name: app-node
    depends_on:
      - rabbitmq
      - mysql
    env_file: ./env/node.env

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
